### ISSUE TITLE
Option --additional-fonts doesn't work

### ISSUE THREAD

**Issue by szyha** [moi15moi/FontCollector#13]
In the latest version 2.0.2, the ``--additional-fonts`` function does not work. I get an error every time.
I have the font collections on another disk, I get this error:

```
C:\Users\xyz\Desktop\Subs>fontcollector -i --additional-fonts D:\Junk\Fonts\
Traceback (most recent call last):
  File "C:\Users\xyz\scoop\apps\Python\current\Scripts\fontcollector-script.py", line 33, in <module>
    sys.exit(load_entry_point('FontCollector==2.0.2', 'console_scripts', 'fontcollector')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\scoop\apps\Python\current\Lib\site-packages\font_collector\__main__.py", line 23, in main
    ) = parse_arguments()
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\scoop\apps\Python\current\Lib\site-packages\font_collector\parse_arguments.py", line 121, in parse_arguments
    additional_fonts = FontLoader.load_additional_fonts(args.additional_fonts)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\scoop\apps\Python\current\Lib\site-packages\font_collector\font_loader.py", line 124, in load_additional_fonts
    additional_fonts.update(Font.from_font_path(path))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\scoop\apps\Python\current\Lib\site-packages\font_collector\font.py", line 72, in from_font_path
    axis_value_tables = ParseFont.get_axis_value_from_coordinates(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\scoop\apps\Python\current\Lib\site-packages\font_collector\parse_font.py", line 132, in get_axis_value_from_coordinates
    raise ValueError("Cannot get axis_value since there is no STAT table.")
ValueError: Cannot get axis_value since there is no STAT table.
```

Also I tested what if the fonts were on the same drive as the subtitles, an error appears interestingly it is different from the first case.

```
C:\Users\xyz\Desktop\Subs>fontcollector -i --additional-fonts ..\Fonts\
Traceback (most recent call last):
  File "C:\Users\xyz\scoop\apps\Python\current\Scripts\fontcollector-script.py", line 33, in <module>
    sys.exit(load_entry_point('FontCollector==2.0.2', 'console_scripts', 'fontcollector')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\scoop\apps\Python\current\Lib\site-packages\font_collector\__main__.py", line 25, in main
    font_collection = FontLoader(additional_fonts, use_system_font).fonts
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\scoop\apps\Python\current\Lib\site-packages\font_collector\font_loader.py", line 29, in __init__
    self.additional_fonts = FontLoader.load_additional_fonts(additional_fonts_path)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xyz\scoop\apps\Python\current\Lib\site-packages\font_collector\font_loader.py", line 120, in load_additional_fonts
    if os.path.isfile(font_path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not Font
```

**Comment by moi15moi** [comment]
Could you share the font that cause the first error?

**Comment by moi15moi** [comment]
Could you tell me if this code works for you? https://github.com/moi15moi/FontCollector/tree/Correct-variable-font-and-loading-font-via-cmd

Download it and install it with ``pip install -e .``
