### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Animorphs** [moi15moi/FontCollector#6]
When attempting to execute fontCollector, I encounter a traceback error. I have the most recent version of fontCollector (1.2.1), so not sure what's going wrong.

```
D:\Downloads\test>fontCollector -i "animorphs_01.ass" -o
Loaded successfully animorphs_01.ass
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "C:\Users\Animorphs\AppData\Local\Programs\Python\Python39\Scripts\fontCollector-script.py", line 33, in <module>
    sys.exit(load_entry_point('fontCollector==1.2.1', 'console_scripts', 'fontCollector')())
  File "c:\users\animorphs\appdata\local\programs\python\python39\lib\site-packages\fontCollector.py", line 630, in main
    fontCollection = initializeFontCollection(additionalFonts)
  File "c:\users\animorphs\appdata\local\programs\python\python39\lib\site-packages\fontCollector.py", line 480, in initializeFontCollection
    font = createFont(fontPath)
  File "c:\users\animorphs\appdata\local\programs\python\python39\lib\site-packages\fontCollector.py", line 438, in createFont
    isItalic = bool(fontTtLib["OS/2"].fsSelection & 1)
  File "C:\Users\animorphs\AppData\Roaming\Python\Python39\site-packages\fontTools\ttLib\ttFont.py", line 362, in __getitem__
    table = self._readTable(tag)
  File "C:\Users\animorphs\AppData\Roaming\Python\Python39\site-packages\fontTools\ttLib\ttFont.py", line 369, in _readTable
    data = self.reader[tag]
  File "C:\Users\animorphs\AppData\Roaming\Python\Python39\site-packages\fontTools\ttLib\sfnt.py", line 105, in __getitem__
    entry = self.tables[Tag(tag)]
KeyError: 'OS/2'
```

I've also tried it with a very simple ass file just in case, which solely consists of the following, but the same error occurs:
```
[Script Info]
; Script generated by Aegisub 9213, Daydream Cafe Edition [Shinon]
; http://www.aegisub.org/
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[Aegisub Project Garbage]

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Gandhi Sans,74,&H00FFFFFF,&H000000FF,&H00000000,&HA0000000,-1,0,0,0,100,100,0,0,1,3.6,1.5,2,180,180,56,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:05.00,0:00:10.00,Default,,0,0,0,,Test.
```

Any help is appreciated, thanks

**Comment by moi15moi** [comment]
This is a silly bug.

When you start FontCollector, it will load all the font in your computer.
Currently, you have one font that has a malformated os/2 table and it make the program crash.

The be able to know which font make crash the program, add ``print(fontPath)`` at this line: https://github.com/moi15moi/FontCollector/blob/f83e9f132d2cfd27bb2b7d03cbac1a49ea5859b5/fontCollector.py#L381

Take the last font that is been printed and send it on github.

I really need your collaboration, because I can do nothing without the font.

Thank you to have reported this issue

**Comment by Animorphs** [comment]
Ah great, thank you! I uninstalled the last font that printed on that list and it works perfectly now.
I've attached it as well so you can take a look at it and maybe create a workaround.

[BRUSHSTP.zip](https://github.com/moi15moi/FontCollector/files/9131403/BRUSHSTP.zip)
